---
ID: "452a541c-7515-46a7-9ddf-f1b5eb48fffd"
Parent: "5cfe7724-a32c-423e-b8f9-12d56cc5a4be"
Template: "5cfe7724-a32c-423e-b8f9-12d56cc5a4be"
Path: /sitecore/templates/Project/UniPaper/Page Design Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {5CFE7724-A32C-423E-B8F9-12D56CC5A4BE}
    {0BE9304A-E858-4C7A-B9F3-A372B01DCFAC}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240622T093243Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3170af8c-ce4a-4248-b851-611cf77ced2b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240622T093249Z
